config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/team'
  get 'welcome/help'

  resources :tags do
    resources :events
    get :newEvent, to: "tags#newEvent"
  end
  
  resources :events
  
  resources :calendar_views do
    get :previousMonth
    get :nextMonth
    get :thisMonth
    get :selectMonth
  end

  root 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar_view.rb
class CalendarView < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :tag
  validates :title, :eventDate, :startTime, :endTime, presence: true
  validates :title, length: { maximum: 50 }
  validates :location, length: { maximum: 50 }
  validate :validStartAndEndTime
  
  def validStartAndEndTime
    if self.startTime <= self.endTime
        return true
    else
        self.errors[:base] << "Your staring time must be before your ending time!"
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :events
    validates_associated :events
    validates :tagName, presence: true, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendar_views_controller.rb
class CalendarViewsController < ApplicationController
    def index
        @dateInUse = CalendarView.find(1).dateInUse
        
        if @dateInUse.nil?
            CalendarView.create(:dateInUse => Date.today)
            @dateInUse = CalendarView.find(1).dateInUse
        end
    end
    
    def show
        @dateForShow = params[:day]
        @events = Event.where(:eventDate => @dateForShow)
    end
    
    def new
        @dayHolder = Date.parse(params[:day])
        @day = @dayHolder.day
        @month = @dayHolder.month
        @year = @dayHolder.year
        
        # Make sure the General tag exists.
        if Tag.count == 0
            Tag.create(:tagName => "General", :description => "This is the default tag for your events.")
        end
        
        @event = Event.new
    end
    
    def previousMonth
        @dateHolder = CalendarView.find(1).dateInUse - 1.month
        CalendarView.find(1).update(:dateInUse => @dateHolder)
        redirect_to calendar_views_path
    end
    
    def nextMonth
        @dateHolder = CalendarView.find(1).dateInUse + 1.month
        CalendarView.find(1).update(:dateInUse => @dateHolder)
        redirect_to calendar_views_path
    end
    
    def thisMonth
        if CalendarView.count == 0
            CalendarView.create(:dateInUse => Date.today)
        end
        
        if CalendarView.find(1).dateInUse != Date.today
            CalendarView.find(1).update(:dateInUse => Date.today)
        end
        
        redirect_to calendar_views_path
    end
    
    def selectMonth
        @calendar_view ||= nil
        @monthHolder = params[:monthParam]
        @yearHolder = params[:yearParam]
        @dateHolder = Date.parse('1-'+@monthHolder.to_s+'-'+@yearHolder.to_s)
        CalendarView.find(1).update(:dateInUse => @dateHolder)
        redirect_to calendar_views_path
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        if params[:filter] != nil
            @events = Event.where(["eventDate >= ?", Date.today])
        else
            @events = Event.all
        end
    end
    
    def show
        @event = Event.find(params[:id])
    end
    
    def new
        # Make sure the General tag exists.
        if Tag.count == 0
            Tag.create(:tagName => "General", :description => "This is the default tag for your events.")
        end
        
        @event = Event.new
    end
    
    def create
        @tag = Tag.find(params[:event][:tag_id])
        @event = @tag.events.create(event_params)
       
        if @event.save
            redirect_to @event
        else
            render 'new'
        end
    end
    
    def edit
        @event = Event.find(params[:id])
    end
    
    def update
        @event = Event.find(params[:id])
        
        if @event.update(event_params)
            redirect_to @event
        else
            render 'edit'
        end
    end
    
    def destroy
        @event = Event.find(params[:id])
        @event.destroy
        
        redirect_to events_path
    end
end

private
    def event_params
        params.require(:event).permit(:title, :location, :eventInformation, :eventDate, :startTime, :endTime, :tag_id)
    end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
        
        if Tag.count == 0
           Tag.create(:tagName => "General", :description => "This is the default tag for your events.")
        end
    end
    
    def show
        @tag = Tag.find(params[:id])
    end
    
    def new
        @tag = Tag.new
    end
    
    def create
        @tag = Tag.new(tag_params)
       
        if @tag.save
            redirect_to @tag
        else
            render 'new'
        end
    end
    
    def edit
        @tag = Tag.find(params[:id])
    end
    
    def update
        @tag = Tag.find(params[:id])
        
        if @tag.update(tag_params)
            redirect_to @tag
        else
            render 'edit'
        end
    end
    
    def destroy
        # Find the tag.
        @tag = Tag.find(params[:id])
        
        # Make sure the General tag can't be maliciously destroyed.
        if @tag.id == 1
           redirect_to tags_path 
        end
        
        # Assign any events associated to the delete tag to the General tag.
        @tagEvents = Tag.find(params[:id]).events
        @tagEvents.update(:tag_id => 1)
        
        # Destroy the tag.
        @tag.destroy
        
        redirect_to tags_path
    end
    
    def newEvent
        @tag = Tag.find(params[:tag_id])
        
        # Make sure the General tag exists.
        if Tag.count == 0
            Tag.create(:tagName => "General", :description => "This is the default tag for your events.")
        end
        
        @event = Event.new
    end
end

private
    def tag_params
       params.require(:tag).permit(:tagName, :description) 
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.where(:eventDate => Date.today)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_views_helper.rb
module CalendarViewsHelper
end

app/helpers/events_helper.rb
module EventsHelper
    
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calendar_views/_calendarLayout.html.erb
<!-- Declare variables -->
<% activeMonth = @dateInUse.month %>
<% activeYear = @dateInUse.year %>
<% firstDate = Date.parse('1-'+activeMonth.to_s+'-'+activeYear.to_s) %>
<% numOfDaysInMonth = Time.days_in_month(activeMonth, activeYear) %>
<% case firstDate.cwday %>
<% when 1..6 %>
<%     startingPos = firstDate.cwday + 1 %>
<% else %>
<%     startingPos = 1 %>
<% end %>
<% dayNum = 1 %>

<table class="calendarLayout">
    <tr>
        <th>S</th>
        <th>M</th>
        <th>T</th>
        <th>W</th>
        <th>T</th>
        <th>F</th>
        <th>S</th>
    </tr>
    <tr>
        <% for i in 1..7 %>
            <% if i < startingPos %>
                <td class="inactive"></td>
            <% else %>
                <% dayHolder = Date.parse(dayNum.to_s+'-'+activeMonth.to_s+'-'+activeYear.to_s) %>
                <td>
                    <div class="dayNumber">
                        <!-- addEventButton -->
                        <%= link_to "+", new_calendar_view_path(day: dayHolder), { :class => "addEventButton" } %>
                        <%= dayNum %>
                    </div>
                    
                    <% numOfEvents = Event.where(:eventDate => dayHolder).count %>
                    <% if numOfEvents != 0 %>
                        <%= link_to"Events: #{ Event.where(:eventDate => dayHolder).count }&nbsp;<i class='fas fa-eye'></i>".html_safe, 
                            calendar_view_path(:calendar_view_id, day: dayHolder), 
                            :class => "dayInfo", 
                            :title => "View Events" %>
                    <% end %>
                </td>
                <% dayNum += 1 %>
            <% end %>
        <% end %>
    </tr>
    <% for week in 2..6 %>
        <tr>
            <% for day in 1..7 %>
                <% if dayNum <= numOfDaysInMonth %>
                    <% dayHolder = Date.parse(dayNum.to_s+'-'+activeMonth.to_s+'-'+activeYear.to_s) %>
                    <td>
                        <div class="dayNumber">
                            <%= link_to "+", new_calendar_view_path(day: dayHolder), { :class => "addEventButton" } %>
                            <%= dayNum %>
                        </div>
                        
                        <% numOfEvents = Event.where(:eventDate => dayHolder).count %>
                        <% if numOfEvents != 0 %>
                            <%= link_to"Events: #{ Event.where(:eventDate => dayHolder).count }&nbsp;<i class='fas fa-eye'></i>".html_safe, 
                                calendar_view_path(:calendar_view_id, day: dayHolder), 
                                :class => "dayInfo", 
                                :title => "View Events" %>
                        <% end %>
                    </td>
                    <% dayNum += 1 %>
                <% else %>
                    <td class="inactive"></td>
                <% end %>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/calendar_views/show.html.erb
<div class="backgroundScene"></div>
<div class="shell">
    <div class="container">
        <div class="header">
            <h1>Events on <%= Date.parse(@dateForShow).strftime("%m/%d/%Y") %></h1>
        </div>
        
        <div class="nav">
            <a href="/../welcome/index.html" class="navButton">Home</a>
            <%= link_to 'Calendar', calendar_view_thisMonth_path(:calendar_view_id), { :class => "navButton active" } %>
            <%= link_to 'Events', events_path, { :class => "navButton" } %>
            <%= link_to 'Tags', tags_path, { :class => "navButton" } %>
            <a href="/../welcome/team.html" class="navButton">Team</a>
            <a href="/../welcome/help.html" class="navButton">Help</a>
        </div>
        
        <div class="content">
            <div class="eventsListContainer">
                <% @events.order(:eventDate).order(:startTime).each do |event| %>
                    <div class="eventsBox">
                        <div class="indicator"></div>
                        <%= link_to'<i class="fas fa-eye"></i>'.html_safe, event_path(event), :title => "Show Event", :class => "viewBox" %>
                        <%= link_to'<i class="fas fa-edit"></i>'.html_safe, edit_event_path(event), :title => "Edit Event", :class => "editBox" %>
                        <%= link_to'<i class="fas fa-trash-alt"></i>'.html_safe, 
                                                                                event_path(event),
                                                                                method: :delete,
                                                                                data: { confirm: 'Are you sure you want to delete this event?' },
                                                                                :title => "Delete Event",
                                                                                :class => "deleteBox" %>
                        <div class="verticalBox1">
                            <div class="eventsTitleBox">
                                <%= event.title %>
                            </div>
                            <div class="eventsInfoBox1">
                                <% if event.location.blank? == false %>
                                    <%= event.location %>&nbsp;|
                                <% end %>
                                <%= event.tag.tagName %>
                            </div>
                            <div class="eventsInfoBox2">
                                <%= event.startTime.strftime("%I:%M %p") %> 
                                - 
                                <%= event.endTime.strftime("%I:%M %p") %>
                            </div>
                        </div>
                        <div class="verticalBox2">
                            <div class="informationTitleBox">
                                <% if event.eventInformation.blank? == false %>
                                    Event Information
                                <% end %>
                            </div>
                            <div class="informationInfoBox">
                                <%= truncate(event.eventInformation, length: 80, separator: ' ', omission: '... (continued)') %>
                            </div>
                        </div>
                        <div class="cap"></div>
                    </div>
                <% end %>
            </div>
            <%= link_to 'Back to Calendar', calendar_views_path(:calendar_view_id), { :class => "basicButton1" } %>
            <%= link_to "Add Event on #{ Date.parse(@dateForShow).strftime("%m/%d/%Y") }", new_calendar_view_path(day: @dateForShow), { :class => "basicButton2" } %>
        </div>
    </div>
</div>

app/views/events/index.html.erb
<div class="backgroundScene"></div>
<div class="shell">
    <div class="container">
        <div class="header">
            <h1>Your Events</h1>
        </div>
        
        <div class="nav">
            <a href="/../welcome/index.html" class="navButton">Home</a>
            <%= link_to 'Calendar', calendar_view_thisMonth_path(:calendar_view_id), { :class => "navButton" } %>
            <%= link_to 'Events', events_path, { :class => "navButton active" } %>
            <%= link_to 'Tags', tags_path, { :class => "navButton" } %>
            <a href="/../welcome/team.html" class="navButton">Team</a>
            <a href="/../welcome/help.html" class="navButton">Help</a>
        </div>
        
        <div class="content">
            <div class="eventsListContainer">
                <% if @events.count == 0 %>
                    <div class="noEvents">
                        <br><br><br><br>
                        <i class="fa fa-calendar-times-o"></i>
                        <% if @events == Event.where(["eventDate >= ?", Date.today]) %>
                            <h1>You don't have any upcoming events!</h1>
                            <h2>Go ahead and click the button below to add an event.</h2>
                        <% else %>
                            <h1>You don't have any events yet!</h1>
                            <h2>Go ahead and click the button below to add your first event.</h2>
                        <% end %>
                    </div>
                <% else %>
                    <% @events.order(:eventDate).order(:startTime).each do |event| %>
                        <div class="eventsBox">
                            <div class="indicator"></div>
                            <%= link_to'<i class="fas fa-eye"></i>'.html_safe, event_path(event), :title => "Show Event", :class => "viewBox" %>
                            <%= link_to'<i class="fas fa-edit"></i>'.html_safe, edit_event_path(event), :title => "Edit Event", :class => "editBox" %>
                            <%= link_to'<i class="fas fa-trash-alt"></i>'.html_safe, 
                                                                                    event_path(event),
                                                                                    method: :delete,
                                                                                    data: { confirm: 'Are you sure you want to delete this event?' },
                                                                                    :title => "Delete Event",
                                                                                    :class => "deleteBox" %>
                            <div class="verticalBox1">
                                <div class="eventsTitleBox">
                                    <%= event.title %>
                                </div>
                                <div class="eventsInfoBox1">
                                    <% if event.location.blank? == false %>
                                        <%= event.location %>&nbsp;|
                                    <% end %>
                                    <%= event.tag.tagName %>
                                </div>
                                <div class="eventsInfoBox2">
                                    <%= event.eventDate.strftime("%m/%d/%Y") %> 
                                    from 
                                    <%= event.startTime.strftime("%I:%M %p") %> 
                                    - 
                                    <%= event.endTime.strftime("%I:%M %p") %>
                                </div>
                            </div>
                            <div class="verticalBox2">
                                <div class="informationTitleBox">
                                    <% if event.eventInformation.blank? == false %>
                                        Event Information:
                                    <% end %>
                                </div>
                                <div class="informationInfoBox">
                                    <%= truncate(event.eventInformation, length: 80, separator: ' ', omission: '... (continued)') %>
                                </div>
                            </div>
                            <div class="cap"></div>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <%= link_to 'New Event', new_event_path, { :class => "basicButton1" } %>
            <% if @events == Event.where(["eventDate >= ?", Date.today]) %>
                <%= link_to 'Show All Events', events_path, { :class => "basicButton2" } %>
            <% else %>
                <%= link_to 'Only Show Upcoming Events', events_path(filter: Date.today), { :class => "basicButton2" } %>
            <% end %>
        </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>eVents</title>
    <%= csrf_meta_tag %> 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<div class="backgroundScene"></div>
<div class="shell">
    <div class="container">
        <div class="header">
            <h1>Your Tags</h1>
        </div>
        
        <div class="nav">
            <a href="/../welcome/index.html" class="navButton">Home</a>
            <%= link_to 'Calendar', calendar_view_thisMonth_path(:calendar_view_id), { :class => "navButton" } %>
            <%= link_to 'Events', events_path, { :class => "navButton" } %>
            <%= link_to 'Tags', tags_path, { :class => "navButton active" } %>
            <a href="/../welcome/team.html" class="navButton">Team</a>
            <a href="/../welcome/help.html" class="navButton">Help</a>
        </div>
        
        <div class="content">
            <div class="tagsListContainer">
                <% @tags.each do |tag| %>
                    <% if tag.id == 1 %>
                        <div class="tagsBox1">
                            <div class="indicator"></div>
                            <%= link_to'<i class="fas fa-eye"></i>'.html_safe, tag_path(tag), :title => "Show Tag", :class => "viewBox" %>
                            <div class="tagVerticalBox1">
                                <div class="tagTitleBox">
                                    <%= tag.tagName %>
                                </div>
                                <div class="tagCountBox">
                                    Number of Events: <%= tag.events.count %>
                                </div>
                            </div>
                            <div class="tagVerticalBox2">
                                <div class="informationTitleBox">
                                    <% if tag.description.blank? == false %>
                                        Tag Information:
                                    <% end %>
                                </div>
                                <div class="informationInfoBox">
                                    <%= truncate(tag.description, length: 80, separator: ' ', omission: '... (continued)') %>
                                </div>
                            </div>
                            <div class="cap"></div>
                        </div>
                    <% else %>
                        <div class="tagsBox">
                            <div class="indicator"></div>
                            <%= link_to'<i class="fas fa-eye"></i>'.html_safe, tag_path(tag), :title => "Show Tag", :class => "viewBox" %>
                            <%= link_to'<i class="fas fa-edit"></i>'.html_safe, edit_tag_path(tag), :title => "Edit Tag", :class => "editBox" %>
                            <%= link_to'<i class="fas fa-trash-alt"></i>'.html_safe, 
                                                                                tag_path(tag),
                                                                                method: :delete,
                                                                                data: { confirm: 'Are you sure you want to delete this tag?' },
                                                                                :title => "Delete Tag",
                                                                                :class => "deleteBox",
                                                                                authenticity_token: true %>
                            <div class="tagVerticalBox1">
                                <div class="tagTitleBox">
                                    <%= tag.tagName %>
                                </div>
                                <div class="tagCountBox">
                                    Number of Events: <%= tag.events.count %>
                                </div>
                            </div>
                            <div class="tagVerticalBox2">
                                <div class="informationTitleBox">
                                    <% if tag.description.blank? == false %>
                                        Tag Information:
                                    <% end %>
                                </div>
                                <div class="informationInfoBox">
                                    <%= truncate(tag.description, length: 80, separator: ' ', omission: '... (continued)') %>
                                </div>
                            </div>
                            <div class="cap"></div>
                        </div>
                    <% end %>
                <% end %>
            </div>
            
            <%= link_to 'New Tag', new_tag_path, { :class => "basicButton" } %>
        </div>
    </div>
</div>

app/views/tags/show.html.erb
<div class="backgroundScene"></div>
<div class="shell">
    <div class="container">
        <div class="header">
            <h1><%= @tag.tagName %></h1>
        </div>
        
        <div class="nav">
            <a href="/../welcome/index.html" class="navButton">Home</a>
            <%= link_to 'Calendar', calendar_view_thisMonth_path(:calendar_view_id), { :class => "navButton" } %>
            <%= link_to 'Events', events_path, { :class => "navButton" } %>
            <%= link_to 'Tags', tags_path, { :class => "navButton active" } %>
            <a href="/../welcome/team.html" class="navButton">Team</a>
            <a href="/../welcome/help.html" class="navButton">Help</a>
        </div>
        
        <div class="showContent">
            <div class="infoContainer">
                <div class="showShell">
                    <div class="startCap"></div>
                    <div class="box1">
                        <div class="tagDescriptionHeader">
                            Description
                        </div>
                        <div class="tagDescriptionInfo">
                            <%= simple_format(@tag.description) %>
                        </div>
                    </div>
                    <div class="box2">
                        <div class="tagEventsHeader">
                            Associated Events
                        </div>
                        <div class="tagEventsInfo">
                            <% if @tag.events.count == 0 %>
                                <div class="tagEventsNoInfo">
                                    <br>
                                    <i class="fa fa-calendar-times-o"></i>
                                    <h2>
                                        This tag doesn't
                                        <br>
                                        have any associated
                                        <br>
                                        events yet.
                                    </h2>
                                </div>
                            <% else %>
                                <% @tag.events.order(:eventDate).each do |event| %>
                                    <div class="tagEventsBox">
                                        <div class="indicator"></div>
                                        <%= link_to'<i class="fas fa-eye"></i>'.html_safe, event_path(event), :title => "Show Event", :class => "viewBox" %>
                                        <div class="titleBox">
                                            <%= event.title %>
                                        </div>
                                        <div class="infoBox1">
                                            <% if event.location.blank? == false %>
                                                <%= event.location %>&nbsp;|
                                            <% end %>
                                            <%= event.tag.tagName %>
                                        </div>
                                        <div class="infoBox2">
                                            <%= event.eventDate.strftime("%m/%d/%Y") %> from <%= event.startTime.strftime("%I:%M %p") %> - <%= event.endTime.strftime("%I:%M %p") %>
                                        </div>
                                    </div>
                                    <br>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                    <div class="cap"></div>
                </div>
                
                
                <% if @tag.id == 1 %>
                    <div class="optionsBoxInactive">
                        <div class="startCap"></div>
                        <%= link_to'<i class="fa fa-calendar-plus-o" aria-hidden="true"></i>'.html_safe, tag_newEvent_path(@tag), :title => "Add Event", :class => "newBoxTag" %>
                        <div class="inactiveButtons">
                            <div class="editInactive">
                                <i class="fas fa-edit"></i>
                            </div>
                            <div class="deleteInactive">
                                <i class="fas fa-trash-alt"></i>
                            </div>
                        </div>
                    </div>
                <% else %>
                    <div class="tagOptionsBox">
                        <div class="startCap"></div>
                        <%= link_to'<i class="fa fa-calendar-plus-o" aria-hidden="true"></i>'.html_safe, tag_newEvent_path(@tag), :class => "newBoxTag" %>
                        <%= link_to'<i class="fas fa-edit"></i>'.html_safe, edit_tag_path(@tag), :class => "editBoxTag" %>
                        <%= link_to'<i class="fas fa-trash-alt"></i>'.html_safe, 
                                                                        tag_path(@tag),
                                                                        method: :delete,
                                                                        data: { confirm: 'Are you sure you want to delete this tag?' },
                                                                        :class => "deleteBoxTag" %>
                    </div>
                <% end %>
            </div>
            
            <%= link_to 'Back to Tags', tags_path, { :class => "basicButton" } %>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="backgroundScene"></div>
<div class="welcomeContainer">
    <div class="welcomeBox">
        <div class="welcomeBoxLogo">
            <i class="fa fa-calendar-o" aria-hidden="true" fa-lg></i>
        </div>
        <br>
        <div class="welcomeBoxName">
            eVents
        </div>
    </div>
    <%= link_to 'Enter', calendar_view_thisMonth_path(:calendar_view_id), { :class => "welcomeButton" } %>
    <div class="todaysEvents">
        <div class="todaysEventsHeader">
            <h1>Today's Events:</h1>
        </div>
        <div class="todaysEventsInfo">
            <% if @events.count == 0 %>
                <div class="todaysEventsNoInfo">
                    <br>
                    <i class="fa fa-calendar-times-o"></i>
                    <h2>
                        You don't have
                        <br>
                        any events today.
                    </h2>
                </div>
            <% else %>
                <% @events.order(:startTime).each do |event| %>
                    <div class="todaysEventsBox">
                        <div class="indicator"></div>
                        <%= link_to'<i class="fas fa-eye"></i>'.html_safe, event_path(event), :title => "Show Event", :class => "viewBox" %>
                        <div class="titleBox">
                            <%= event.title %>
                        </div>
                        <div class="infoBox1">
                            <% if event.location.blank? == false %>
                                <%= event.location %>&nbsp;|
                            <% end %>
                            <%= event.tag.tagName %>
                        </div>
                        <div class="infoBox2">
                            From <%= event.startTime.strftime("%I:%M %p") %> - <%= event.endTime.strftime("%I:%M %p") %>
                        </div>
                        <div class="cap"></div>
                    </div>
                    <br>
                <% end %>
            <% end %>
        </div>
    </div>
</div>